sources:
  - Sources
  - ../Sources/Beagle/CodeGeneration/SourceryProtocols.swift
templates:
  - ../Sources/Beagle/CodeGeneration/Templates
output:
  Sources/CodeGeneration/Generated
args:
  shouldNotImportBeagle: 1
