sources:
  - Sources
  - ../Sources/Beagle/CodeGeneration/SourceryProtocols.swift
  - ../../schema/schema-ruby-erb/model_generation/Generated/Swift/FromRubySchema
templates:
  - ../Sources/Beagle/CodeGeneration/Templates
output:
  Sources/CodeGeneration/Generated
args:
  shouldNotImportBeagle: 1
