name: 'AWS Secrets Manager Action'
author: 'Abhilash Kishore'
description: 'Use secrets from AWS Secrets Manager as environment variables in your GitHub Actions workflow'
inputs:
  aws-access-key-id:
    description: 'Access Key ID of the IAM user with the required AWS Secrets Manager permissions'
    required: true
  aws-secret-access-key:
    description: 'Corresponding Secret Access Key of the IAM user with the required AWS Secrets Manager permissions'
    required: true
  aws-session-token:
    description: '(Optional) Corresponding Session Token of the IAM user session with the required AWS Secrets Manager permissions'
    required: false
  aws-region:
    description: 'The region of AWS Secrets Manager which contains your secrets (e.g.: us-east-1)'
    required: true
  secrets:
    description: 'List of secret names you want to fetch secret values for'
    required: true
  parse-json:
    description: 'If true and secret values are stringified JSON objects, they will be parsed and flattened. Its key value pairs will become individual secrets'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: lock
  color: blue
