# Make it more obvious that a PR is a work in progress and shouldn't be merged yet.
has_wip_label = github.pr_labels.any? { |label| label.include? "WIP" }
has_wip_title = github.pr_title.include? "[WIP]"

if has_wip_label || has_wip_title
	warn("PR is classed as Work in Progress")
end

# Warn when there is a big PR.
warn("Big PR") if git.lines_of_code > 300

if github.pr_body.length < 2 && git.lines_of_code > 10
  warn("Please provide a summary in the Pull Request description")
end

def match_semantic_pr_title(text)
  text.match(/^(?<type>\w+)(?:\((?<scope>.+?)\))?:(?<description>.+?)$/)
end

SEMANTIC_PR_TYPES = %w[build chore ci docs feat fix perf refactor revert style test].freeze

semantic_pr_title = match_semantic_pr_title(github.pr_title)
if !semantic_pr_title || !SEMANTIC_PR_TYPES.include?(semantic_pr_title[:type])
 fail("The title of PR not follow the rules of: https://www.conventionalcommits.org/en/v1.0.0/")
end
