name: Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:

jobs:
  # unit tests
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test

  integration-test-latest:
    # Run only on 'push' or 'pull_request within same repository (not from a fork)'
    # since workflows triggered for PRs from a fork will not have access to GitHub secrets
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.base.repo.html_url == github.event.pull_request.head.repo.html_url) }}
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        secrets: '*secret*'
        parse-json: true

  integration-test-release:
    # Run only on 'push' or 'pull_request within same repository (not from a fork)'
    # since workflows triggered for PRs from a fork will not have access to GitHub secrets
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.base.repo.html_url == github.event.pull_request.head.repo.html_url) }}
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: action-factory/aws-secrets-manager-action@v1.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        secrets: 'my_secret*'
        parse-json: true
