include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    constant_identifier_names: false
