sources:
  - BeagleDemo
  - BeagleDemo/../../../Sources/BeagleUI/SourceryFiles/SourceryProtocols.swift
templates:
  - BeagleDemo/../../../Sources/BeagleUI/SourceryFiles/Templates
output:
  BeagleDemo/SourceryFiles
