###
###  Android
###

platform :android do

  desc "Pull Request verification"
  lane :pull_request_verification do
    gradle(project_dir: "android", task: "detekt lintDebug jacocoTestReport")
    gradle(project_dir: "android", task: "sample:assembleDebug sample:assembleDebugAndroidTest")
    run_codecov(platform: 'android')
  end

end

###
###  Common (Android and Backend)
###

platform :common do

  desc "Publish remote new version"
  lane :remote_publish do
    sh "./release/signing.sh"
    # gradle(task: "publish")
  end

   desc "Publish local new version"
    lane :local_publish do
      gradle(task: "build")
      gradle(task: "publishToMavenLocal")
    end

end

###
###  iOS
###

platform :ios do

  desc "Pull Request verification"
  lane :pull_request_verification do
    xcversion(version: "~> 11.5.0")
    iOSSwiftLint
    scan(
      workspace: "iOS/Beagle.xcworkspace/",
      scheme: "All",
      device: "iPhone 11"
    )
    run_codecov(platform: 'ios')
  end

  desc "Run iOS SwiftLint"
  private_lane :iOSSwiftLint do
    swiftlint(
    mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
    ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
  )
  end

  desc "Updates versions on Podspec"
  lane :release do
    version_bump_podspec(path: "Beagle.podspec", version_number: last_git_tag)
    version_bump_podspec(path: "BeagleSchema.podspec", version_number: last_git_tag)
    pod_push(path: "BeagleSchema.podspec", allow_warnings: true)
    pod_push(path: "Beagle.podspec", allow_warnings: true)
  end

end

desc "Publish new release based on last two tags"
lane :deploy do
  git_pull
  ENV["VERSION_DEPLOY"] = last_git_tag
  sh "fastlane common remote_publish"
  sh "fastlane ios release"

  sh "bash ./delete_release.sh"
  set_github_release(
    repository_name: "ZupIT/beagle",
    api_token: ENV["REPO_TOKEN"],
    name: ENV["VERSION_DEPLOY"],
    tag_name: ENV["VERSION_DEPLOY"],
    description: release_notes,
    commitish: "master"
  )
  sh "bash ./discord_message.sh"
end

lane :run_danger do |options|
   danger_id = options[:danger_id] || lane_context[SharedValues::PLATFORM_NAME].to_s
   danger_file_path = options[:danger_file_path] || lane_context[SharedValues::PLATFORM_NAME].to_s
   danger(
     danger_id: danger_id,
     dangerfile: "danger/#{danger_file_path}/Dangerfile",
     github_api_token: ENV["GITHUB_TOKEN"],
     verbose: true
    )
end

###
###  Backend
###

platform :backend do

  desc "Pull Request verification"
  lane :pull_request_verification do
    gradle(project_dir: "backend", task: "detekt")
    gradle(project_dir: "backend", tasks:
        [
          "assemble",
          "jacocoTestReport",
        ]
    )
    run_codecov(platform: 'backend')
  end

  desc "Sync Spring BFF sample to Micronaut BFF sample"
  lane :sync_to_micronaut do
    sh "./sync-to-micronaut.sh"
    sh "./git_commit.sh 'Synced Spring BFF sample to Micronaut BFF sample.' '../backend/sample/micronaut'"
    push_to_git_remote
  end

  desc "Sync Micronaut BFF sample to Spring BFF sample"
  lane :sync_to_spring do
    sh "./sync-to-spring.sh"
    sh "./git_commit.sh 'Synced Micronaut BFF sample to Spring BFF sample.' '../backend/sample/spring'"
    push_to_git_remote
  end

end


desc "Generate release notes"
private_lane :release_notes do
  get_previous_tag = sh "bash ./get_previous_tag.sh"

  lane_context[SharedValues::RELEASE_ANALYZED] = true
  lane_context[SharedValues::RELEASE_LAST_TAG_HASH] = get_previous_tag
  lane_context[SharedValues::RELEASE_NEXT_VERSION] = ENV["VERSION_DEPLOY"]
  changelog = conventional_changelog(display_title: false, display_links: false)
  "\nRelease notes #{ ENV["VERSION_DEPLOY"] }
   \nChanges:
   \n#{changelog}"
end

private_lane :run_codecov do |options|
  codecov = ENV["CODECOV_TOKEN"]
  if !(codecov.nil? || codecov.empty?)
     commit_hash = last_git_commit[:commit_hash]
     codecov_reporter(token: codecov, flags: "-F #{options[:platform]} -C #{commit_hash}")
  end
end

private_lane :danger_token_available? do
  danger = ENV["GITHUB_TOKEN"]
  !(danger.nil? || danger.empty?)
end

after_all do |lane, options|
   if lane == :pull_request_verification
       if danger_token_available?
         run_danger
       end
    end
end

error do |lane, exception, options|
  if lane == :pull_request_verification
     if danger_token_available?
       run_danger
     end
  end
end
