target 'CocoaPodsTest' do
  use_frameworks!
  pod 'Beagle', :git => 'https://github.com/ZupIT/beagle.git', :branch => 'master'
  pod 'BeagleSchema', :git => 'https://github.com/ZupIT/beagle.git', :branch => 'master'
end
