name: Beagle Android Pull Request

on:
   pull_request:
     branches: [master]
     paths:
        - 'android/**'
jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install Fastlane
              run: bundle install
            - name: Run pr check
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: bundle exec fastlane android pull_request_verification
        