name: Beagle Automated Tests

on: workflow_dispatch

jobs:
    run-automated-tests:
        name: Run automated tests
        runs-on: macos-latest 

        steps:
            -   uses: actions/checkout@v2

            # Fastlane
            -   name: Cache fastlane dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.gem
                    key: ${{ runner.os }}-build-fastlane-cache-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ runner.os }}-build-fastlane-cache

            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install

            # Backend
            -   name: Cache gradle dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.gradle
                    key: ${{ runner.os }}-build-gradle-cache-${{ hashFiles('backend/buildSrc/**', 'android/buildSrc/**') }}
                    restore-keys: ${{ runner.os }}-build-gradle-cache
                    
            -   name: Start backend in background
                run: bash fastlane/automatedTests/start_test_backend.sh

            # Android
            -   name: Cache android multiple things
                uses: actions/cache@v2
                with:
                    path: |
                        /Users/runner/Library/Android/sdk/platforms
                        /Users/runner/Library/Android/sdk/system-images
                        ~/.android
                    key: ${{ runner.os }}-build-android-cache-${{ hashFiles('fastlane/automatedTests/run_android_automation.sh') }}
            
            -   name: Test Android
                run: bash fastlane/automatedTests/run_android_automation.sh
                env:
                    ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk

            # iOS
            -   name: Test iOS
                run: bundle exec fastlane automated_tests run_ios_automation

            # END
            -   name: Cleanup
                run: bundle exec fastlane automated_tests cleanup
