name: Beagle Backend Pull Request

on:
    pull_request:
        paths:
            - 'backend/**'
            - 'common/**'
            - 'schema/kotlin/**'
            - 'buildSrc/**'
            - 'Gemfile'
jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache dependences
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('**/Gemfile') }}

            -   name: Install Fastlane
                run: bundle config set path ${{ env.fastlane-path }} && bundle install
            -   name: Run pr check
                env:
                    GITHUB_USER: ${{ secrets.NAME_REPO_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
                run: bundle exec fastlane backend pull_request_verification
        