name: Beagle Flutter Pull Request

on:
    push:
        branches:
            - main
        paths:
            - 'flutter/**'
    pull_request:
        paths:
            - 'flutter/**'
            - 'Gemfile'
jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: subosito/flutter-action@v1
                with:
                  channel: 'stable' # or: 'dev' or 'beta'
            -   name: Read secrets from AWS Secrets Manager into environment variables
                uses: abhilash1in/aws-secrets-manager-action@v1.0.1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1
                    secrets: |
                        beagle/core/*
                    parse-json: true

            # Gems for Fastlane
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install gem dependencies
                run: bundle config set path '~/.gem' && bundle install

            -   name: Cache pub dependences
                uses: actions/cache@v2
                env:
                    pub-cache-key: pub-cache
                    pub-path: ~/.pub-cache
                with:
                    path: ${{ env.pub-path }}
                    key: ${{ runner.os }}-build-${{ env.pub-cache-key }}
                    restore-keys: ${{ runner.os }}-build-${{ env.pub-cache-key }}
            -   name: Run pr check
                env:
                    GITHUB_USER: ${{ env.BEAGLE_CORE_GITHUB_GITHUB_USER }}
                    GITHUB_TOKEN: ${{ env.BEAGLE_CORE_GITHUB_GITHUB_TOKEN }}
                run: bundle exec fastlane flutter pull_request_verification
