name: Beagle iOS Pull Request

on:
    push:
        branches:
            - master
        paths:
            - 'iOS/**'
    pull_request:
        # TODO: remove this path selector when we have more integrated tests
        paths:
            - 'iOS/**'
            - 'Gemfile'
jobs:
    pr_verification:
        name: PR Check
        runs-on: macos-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2

            # Gems for Fastlane
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems-testing
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install gem dependencies
                run: bundle config set path '~/.gem' && bundle install

            # SPM
            -   name: Cache SPM dependencies
                uses: actions/cache@v2
                with:
                    path: ~/**/DerivedData/**/SourcePackages
                    key: ${{ runner.os }}-spm-${{ hashFiles('iOS/**/Package.resolved') }}
                    restore-keys: ${{ runner.os }}-spm

            # Run
            -   name: Run PR Verification
                env:
                    GITHUB_USER: ${{ secrets.NAME_REPO_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
                run: bundle exec fastlane ios pull_request_verification
