name: Beagle iOS Pull Request

on:
    push:
        branches:
            - main
        paths:
            - 'iOS/**'
    pull_request:
        # TODO: remove this path selector when we have more integrated tests
        paths:
            - 'iOS/**'
            - 'Gemfile'
jobs:
    pr_verification:
        name: PR Check
        runs-on: macos-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
                with:
                    fetch-depth: 10 # increase this number when in a PR with many commits
            -   name: Read secrets from AWS Secrets Manager into environment variables
                uses: abhilash1in/aws-secrets-manager-action@v1.0.1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: us-east-1
                    secrets: |
                        beagle/core/*
                    parse-json: true

            # Gems for Fastlane
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install gem dependencies
                run: bundle config set path '~/.gem' && bundle install

            # SPM
            -   name: Cache SPM dependencies
                uses: actions/cache@v2
                with:
                    path: ~/**/DerivedData/**/SourcePackages
                    key: ${{ runner.os }}-spm-${{ hashFiles('iOS/**/Package.resolved') }}
                    restore-keys: ${{ runner.os }}-spm

            # Run
            -   name: Run PR Verification
                env:
                    GITHUB_USER: ${{ env.BEAGLE_CORE_GITHUB_GITHUB_USER }}
                    GITHUB_TOKEN: ${{ env.BEAGLE_CORE_GITHUB_GITHUB_TOKEN }}
                run: bundle exec fastlane ios pull_request_verification
