name: Check License Lines
on: [pull_request]
jobs:
  license-header-check:
    name: License Header Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6
