name: Beagle Post Release

on:
    release
jobs:
    generate-release:
        name: Generate PR Post Release
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2.1.0

            -   name: Cache fastlane dependences
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install


            - name: Install Fastlane
              run: bundle install
            - name: Open Pull Request
              run: bundle exec fastlane openPR paramTag:${{ github.ref }} token:${{ secrets.REPO_TOKEN }}
        