name: Beagle PR Danger

on:
   pull_request:
       types: [edited, synchronize, reopened, opened]
       branches:
       - master
jobs:
    danger-pr:
        name: Danger PR
        runs-on: macos-10.15
        steps:
            -   uses: actions/checkout@v2

            # Gems for Fastlane
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install gem dependencies
                run: bundle config set path '~/.gem' && bundle install
                
            -   name: Run danger check
                env:
                  GITHUB_USER: ${{ secrets.NAME_REPO_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
                run:  '[ ! -z $GITHUB_TOKEN ] && bundle exec fastlane run_danger danger_id:"pr_danger" danger_file_path:"pr" || echo "Skipping Danger for External Contributor"'
