name: Publish Beagle test backend

on: workflow_dispatch

jobs:
    publish:
        name: Publish test backend to GitHub packages
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache gradle backend dependencies
                uses: actions/cache@v2
                env:
                    gradle-cache-key: backend-tests-gradle-cache
                    gradle-path: ~/.gradle
                with:
                    path: ${{ env.gradle-path }}
                    key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('backend/buildSrc/**') }}
                    restore-keys: ${{ runner.os }}-build-${{ env.gradle-cache-key }}
            -   name: Create backend image and publish it
                run: bash fastlane/automatedTests/publish_test_backend.sh
                env:
                    user: ${{ github.actor }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    repository: ${{ github.repository }}
                    registry: docker.pkg.github.com
                    image: automated-test-backend
