name: Beagle Release

on:
    push:
        tags:
            - '*'
    pull_request:
        branches:
            - master
jobs:
    publish:
        name: Publish kdocs to aws S3
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Cache gradle backend dependencies
              uses: actions/cache@v2
              env:
                  gradle-cache-key: kdocs
                  gradle-path: ~/.gradle
              with:
                  path: ${{ env.gradle-path }}
                  key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('backend/buildSrc/**') }}
                  restore-keys: ${{ runner.os }}-build-${{ env.gradle-cache-key }}
            - name: generate docs android
              run: gradle dokkaHtmlCollector
              working-directory: android
            - name: generate docs backend
              run: gradle dokkaHtmlCollector
              working-directory: backend
            - name: merge docs
              run: bash fastlane/kdocs/merge_docs.sh
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: sa-east-1
            - name: S3 upload (latest version)
              run: aws s3 sync --acl public-read --follow-symlinks public s3://${{ secrets.AWS_S3_DOC_BUCKET }}/ --delete