name: Sync Spring BFF sample to Micronaut BFF sample

on:
    push:
        paths:
            - 'backend/sample/spring/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v1

            -   name: Install Fastlane
                run: bundle install

            -   name: Run pr check
                run: bundle exec fastlane backend sync_to_micronaut
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
