name: Sync to Micronaut BFF sample

on:
    push:
        branches-ignore:
            - master
        paths:
            - 'backend/sample/spring/**'

jobs:
    build:
        runs-on: macos-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache fastlane dependences
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}
            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install

            -   name: Sync Spring BFF sample to Micronaut BFF sample
                run: bundle exec fastlane backend sync_to_micronaut
