name: Sync to Micronaut BFF sample

on:
    push:
        paths:
            - 'backend/sample/spring/**'

jobs:
    build:
        runs-on: macos-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Install Fastlane
                run: bundle install

            -   name: Sync Spring BFF sample to Micronaut BFF sample
                run: bundle exec fastlane backend sync_to_micronaut
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}