name: Sync to Spring BFF sample

on:
    push:
        paths:
            - 'backend/sample/micronaut/**'

jobs:
    build:
        runs-on: macos-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Install Fastlane
                run: bundle install

            -   name: Sync Micronaut BFF sample to Spring BFF sample
                run: bundle exec fastlane backend sync_to_spring
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
