name: Sync Spring BFF sample to Micronaut BFF sample

on:
    push:
        paths:
            - 'backend/sample/spring/**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Sync to Micronaut
                run: cd backend/sample/spring && ./sync-to-micronaut.sh
            -   uses: EndBug/add-and-commit@v4
                with:
                    message: 'Synced Spring BFF sample to Micronaut BFF sample.'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}