name: Sync to Micronaut BFF sample

on:
    push:
        branches-ignore:
            - master
        paths:
            - 'backend/sample/spring/**'

jobs:
    build:
        runs-on: macos-latest

        steps:
            -   uses: actions/checkout@v2

            # Fastlane
            -   name: get github actions image version
                run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems-${{ env.ImageVersion }}
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install

            -   name: Sync Spring BFF sample to Micronaut BFF sample
                run: bundle exec fastlane backend sync_to_micronaut
