name: Sync to Spring BFF sample

on:
    push:
        branches-ignore:
            - master
        paths:
            - 'backend/sample/micronaut/**'

jobs:
    build:
        runs-on: macos-latest

        steps:
            -   uses: actions/checkout@v2

            # Gems for Fastlane
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install gem dependencies
                run: bundle config set path '~/.gem' && bundle install

            -   name: Sync Micronaut BFF sample to Spring BFF sample
                run: bundle exec fastlane backend sync_to_spring
