name: Sync Micronaut BFF sample to Spring BFF sample

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Sync to Spring
              run: cd backend/sample/micronaut && ./sync-to-spring.sh